// ============================================================
// OMAR'S PIE — data.js v1.4.0
// Neapolitan style · Biga dough · Gozney Dome + Baking Steel
// Pork-free · All cuisines · Three stores
// Smart roll engine: flavor contrast · moisture · weight · presence
// ============================================================

const APP_VERSION = "1.4.0";
const APP_NAME    = "Omar's Pie";

// ── STORES ──────────────────────────────────────────────────
const STORES = {
  sara:  { id:"sara",  name:"Sara's Market",  short:"Sara's", color:"#8b2020" },
  cm:    { id:"cm",    name:"Central Market",  short:"CM",     color:"#2d6a2d" },
  altin: { id:"altin", name:"Altin Grocery",   short:"Altin",  color:"#1a4a7a" },
};
const STORE_ORDER = ["sara","cm","altin"];

// ── CUISINES ────────────────────────────────────────────────
const CUISINES = [
  { id:"neapolitan",   label:"Neapolitan",    emoji:"🍅", desc:"San Marzano · fior di latte · basil · EVOO" },
  { id:"levantine",    label:"Levantine",     emoji:"🫓", desc:"Labneh · za'atar · sumac · pomegranate" },
  { id:"turkish",      label:"Turkish",       emoji:"🫕", desc:"Spiced lamb · kashkaval · peppers · yogurt" },
  { id:"greek",        label:"Greek",         emoji:"🫒", desc:"Feta · kalamata · oregano · lemon" },
  { id:"mexican",      label:"Mexican",       emoji:"🌶️", desc:"Chipotle · cotija · jalapeño · cilantro" },
  { id:"american",     label:"American",      emoji:"🧀", desc:"BBQ · aged cheddar · pickled · hot honey" },
  { id:"northafrican", label:"North African", emoji:"🪔", desc:"Harissa · preserved lemon · chermoula · dukkah" },
  { id:"indian",       label:"Indian",        emoji:"🫚", desc:"Tikka masala · paneer · chaat masala · chutney" },
];

const CUISINE_AFFINITIES = [
  ["neapolitan","greek"],["neapolitan","levantine"],
  ["levantine","turkish"],["levantine","greek"],
  ["levantine","northafrican"],["turkish","greek"],
  ["northafrican","levantine"],["northafrican","turkish"],
  ["neapolitan","northafrican"],["neapolitan","turkish"],
];
const CUISINE_CLASHES = [
  ["neapolitan","mexican"],["neapolitan","indian"],["neapolitan","american"],
  ["mexican","indian"],["mexican","northafrican"],
  ["american","indian"],["american","levantine"],["american","northafrican"],
  ["indian","turkish"],["indian","greek"],
];

const CUISINE_LOCKED_SAUCES = new Set([
  "tomatillo_sauce","shakshuka_sauce","roja_sauce",
  "tikka_sauce","makhani_sauce","lahmajun_spread","chipotle_base","biber_salcasi",
]);

// ── PROFILES ────────────────────────────────────────────────
// T = Traditional · E = Elevated · C = Connoisseur
const PROFILE_INCLUDES = {
  traditional:  ["T"],
  elevated:     ["T","E"],
  connoisseur:  ["T","E","C"],
};

// ── LAYER META ──────────────────────────────────────────────
const LAYER_META = {
  base:    { label:"Base",    emoji:"🫙", order:0, note:"Applied to raw dough before sauce" },
  sauce:   { label:"Sauce",   emoji:"🍅", order:1, note:"The identity of the pizza" },
  cheese:  { label:"Cheese",  emoji:"🧀", order:2, note:"On the sauce, under most toppings" },
  protein: { label:"Protein", emoji:"🥩", order:3, note:"Check prep — poultry always pre-cook" },
  veg:     { label:"Veg",     emoji:"🫑", order:4, note:"Some pre-bake, some post — see notes" },
  finish:  { label:"Finish",  emoji:"✨", order:5, note:"Post-bake garnish, drizzle or dusting" },
};
const LAYER_ORDER = ["base","sauce","cheese","protein","veg","finish"];

// ── PREP STATUS ──────────────────────────────────────────────
const PREP = { RAW:"raw-on", PRE:"precook", READY:"readyasis" };

// ── OVEN GUIDANCE ────────────────────────────────────────────
const OVEN_GUIDANCE = {
  dome: {
    id:"dome", label:"Gozney Dome", emoji:"🔥",
    temp:"850–950°F (450–510°C) stone", time:"60–90 seconds",
    tips:[
      "Rotate 45° every 15–20 seconds",
      "Watch for leopard spotting on the crust edge",
      "Open dome lid slightly for even top browning",
      "High-moisture items (bufala, fresh tomato) — post-bake only",
      "Raw-on proteins safe at this temperature with thin application",
    ]
  },
  steel: {
    id:"steel", label:"Baking Steel", emoji:"🪨",
    temp:"550°F (290°C) · top rack · broiler on", time:"4–6 minutes",
    tips:[
      "Preheat steel minimum 1 hour before launch",
      "Launch on parchment, pull paper after 90 seconds",
      "Rotate once at the 3-minute mark",
      "Finish under broiler for top colour",
      "Egg — add at 3-minute mark only for runny yolk",
    ]
  }
};

// ── SAUCE-DRIVEN BUILD PROFILES ──────────────────────────────
// Probability and count rules per sauce family
// prob: 0–1 chance this layer appears at all
// count: [min, max] items if layer appears
const SAUCE_BUILD_PROFILES = {
  tomato: {
    base:    { prob: 0.40, count: [1,1] },
    cheese:  { prob: 0.90, count: [1,1] },
    protein: { prob: 0.65, count: [1,1] },
    veg:     { prob: 0.80, count: [1,3] },
    finish:  { prob: 0.85, count: [1,3] },
    cheeseWeight:  ["anchor"],
    proteinWeight: ["anchor","supporting"],
    vegWeight:     ["supporting","accent"],
    finishWeight:  ["accent"],
  },
  dairy: {
    base:    { prob: 0.60, count: [1,1] },
    cheese:  { prob: 0.95, count: [1,2] },
    protein: { prob: 0.45, count: [1,1] },
    veg:     { prob: 0.85, count: [1,3] },
    finish:  { prob: 0.90, count: [2,3] },
    cheeseWeight:  ["anchor","supporting"],
    proteinWeight: ["accent","supporting"],
    vegWeight:     ["supporting","accent"],
    finishWeight:  ["accent"],
  },
  herb: {
    base:    { prob: 0.55, count: [1,1] },
    cheese:  { prob: 0.85, count: [1,1] },
    protein: { prob: 0.35, count: [1,1] },
    veg:     { prob: 0.90, count: [2,3] },
    finish:  { prob: 0.95, count: [2,3] },
    cheeseWeight:  ["anchor","supporting"],
    proteinWeight: ["accent"],
    vegWeight:     ["supporting","anchor"],
    finishWeight:  ["accent"],
  },
  spicepaste: {
    base:    { prob: 0.30, count: [1,1] },
    cheese:  { prob: 0.80, count: [1,1] },
    protein: { prob: 0.85, count: [1,1] },
    veg:     { prob: 0.65, count: [1,2] },
    finish:  { prob: 0.85, count: [1,2] },
    cheeseWeight:  ["supporting"],
    proteinWeight: ["anchor"],
    vegWeight:     ["accent","supporting"],
    finishWeight:  ["accent"],
  },
  meatbase: {
    base:    { prob: 0.00, count: [0,0] },
    cheese:  { prob: 0.00, count: [0,0] },
    protein: { prob: 0.00, count: [0,0] },
    veg:     { prob: 0.70, count: [1,2] },
    finish:  { prob: 0.90, count: [1,2] },
    vegWeight:     ["accent"],
    finishWeight:  ["accent"],
  },
  nosause: {
    base:    { prob: 0.95, count: [1,1] },
    cheese:  { prob: 1.00, count: [1,2] },
    protein: { prob: 0.50, count: [1,1] },
    veg:     { prob: 0.70, count: [1,2] },
    finish:  { prob: 0.90, count: [2,3] },
    cheeseWeight:  ["anchor","supporting"],
    proteinWeight: ["supporting","accent"],
    vegWeight:     ["supporting","accent"],
    finishWeight:  ["accent"],
  },
};

// ── FLAVOR NOTES ────────────────────────────────────────────
// Used for contrast checking — no note should dominate more than twice
// acid · fat · heat · fresh · crunch · brine · sweet · umami · herb · smoke · cream · spice

// ── MOISTURE LEVELS ──────────────────────────────────────────
// dry · low · medium · high · postbake
// Budget: max 2 high-moisture items pre-bake total

// ── WEIGHT LEVELS ────────────────────────────────────────────
// light · medium · heavy
// Budget tracked across cheese + protein + veg

// ── PRESENCE LEVELS ──────────────────────────────────────────
// anchor · supporting · accent
// Max 1 anchor per layer (except finish which has none)

// ── TOPPINGS ─────────────────────────────────────────────────
// New fields: profile T/E/C, compatibleSauceFamilies (base only),
//             flavorNotes[], moisture, weight, presence
const TOPPINGS = [

  // ══ BASE ════════════════════════════════════════════════════
  {
    id:"evoo_base", name:"EVOO drizzle",
    layer:"base", cuisine:["neapolitan","greek","levantine","turkish","northafrican"],
    profile:"T",
    sauceFamilies:["nosause","dairy","herb","tomato"],
    compatibleSauceFamilies:["tomato","dairy","herb","spicepaste","nosause","meatbase"],
    stores:["sara","cm"],
    flavorNotes:["fat"], moisture:"dry", weight:"light", presence:"accent",
    note:"High-quality — applied before sauce on white pies",
    qty:{ unit:"bottle", yield_g:750, per_pizza_g:15, per_pizza_oz:0.5, per_pizza_tbsp:1, pantry:true, min_purchase:1 },
  },
  {
    id:"garlic_oil", name:"Roasted garlic oil",
    layer:"base", cuisine:["neapolitan","american","greek","levantine"],
    profile:"T",
    sauceFamilies:["nosause","dairy","tomato"],
    compatibleSauceFamilies:["tomato","dairy","nosause","herb"],
    stores:["sara","cm"],
    flavorNotes:["fat","umami"], moisture:"dry", weight:"light", presence:"accent",
    note:"Brush edge to crust — garlic bread effect",
    qty:{ unit:"bottle", yield_g:750, per_pizza_g:10, per_pizza_oz:0.4, per_pizza_tbsp:1, pantry:true, min_purchase:1 },
  },
  {
    id:"zaatar_oil", name:"Za'atar oil",
    layer:"base", cuisine:["levantine","turkish","northafrican","greek"],
    profile:"E",
    sauceFamilies:["nosause","herb","dairy"],
    compatibleSauceFamilies:["dairy","herb","nosause"],
    stores:["sara"],
    flavorNotes:["herb","fat"], moisture:"dry", weight:"light", presence:"accent",
    desc:"Za'atar-infused olive oil — earthy, herbaceous, sesame-nutty. Replaces tomato on white pies.",
    note:"Replaces tomato on white pies — classic manakish base",
    qty:{ unit:"jar (200g)", yield_g:200, per_pizza_g:20, per_pizza_oz:0.7, per_pizza_tbsp:1.5, shared_yield:10, pantry:true, min_purchase:1 },
  },
  {
    id:"harissa_base", name:"Harissa smear (thin)",
    layer:"base", cuisine:["northafrican","levantine","turkish"],
    profile:"E",
    sauceFamilies:["spicepaste","tomato"],
    compatibleSauceFamilies:["tomato","spicepaste"],
    stores:["sara"],
    flavorNotes:["heat","smoke","spice"], moisture:"low", weight:"light", presence:"accent",
    desc:"North African chili paste — spicy, smoky, complex. Apply very thin under or instead of sauce.",
    note:"Very thin layer only — intense heat",
    qty:{ unit:"jar (180g)", yield_g:180, per_pizza_g:15, per_pizza_oz:0.5, per_pizza_tbsp:1, shared_yield:12, pantry:true, min_purchase:1 },
  },
  {
    id:"chipotle_base", name:"Chipotle adobo smear",
    layer:"base", cuisine:["mexican"],
    profile:"E",
    sauceFamilies:["spicepaste"],
    compatibleSauceFamilies:["spicepaste","tomato"],
    stores:["cm"],
    flavorNotes:["smoke","heat","spice"], moisture:"low", weight:"light", presence:"accent",
    desc:"Smoked dried jalapeño in tomato sauce — smoky, earthy, distinctly Mexican.",
    note:"Thin layer — smoke-forward base for Mexican pies",
    qty:{ unit:"can (200g)", yield_g:200, per_pizza_g:20, per_pizza_oz:0.7, shared_yield:10, pantry:true, min_purchase:1 },
  },
  {
    id:"tikka_base", name:"Tikka paste layer",
    layer:"base", cuisine:["indian"],
    profile:"E",
    sauceFamilies:["spicepaste"],
    compatibleSauceFamilies:["spicepaste"],
    stores:["cm"],
    flavorNotes:["spice","heat","umami"], moisture:"low", weight:"light", presence:"accent",
    desc:"Concentrated Indian spice paste — ginger, garlic, cumin, coriander, chili.",
    note:"Mix with yogurt before applying — tempers intensity",
    qty:{ unit:"jar (300g)", yield_g:300, per_pizza_g:25, per_pizza_oz:0.9, shared_yield:12, pantry:true, min_purchase:1 },
  },
  {
    id:"bbq_base", name:"BBQ sauce base",
    layer:"base", cuisine:["american"],
    profile:"T",
    sauceFamilies:["tomato","spicepaste"],
    compatibleSauceFamilies:["nosause","tomato"],
    stores:["cm"],
    flavorNotes:["sweet","smoke","umami"], moisture:"medium", weight:"medium", presence:"anchor",
    note:"Replaces tomato — bold, sweet-smoky",
    qty:{ unit:"bottle (500g)", yield_g:500, per_pizza_g:75, per_pizza_oz:2.6, per_pizza_tbsp:5, pantry:true, min_purchase:1 },
  },
  {
    id:"calabrian_oil_base", name:"Calabrian chili oil (base)",
    layer:"base", cuisine:["neapolitan","american"],
    profile:"E",
    sauceFamilies:["tomato","nosause","spicepaste"],
    compatibleSauceFamilies:["tomato","nosause"],
    stores:["cm"],
    flavorNotes:["heat","fat","smoke"], moisture:"dry", weight:"light", presence:"accent",
    desc:"Italian chili oil from Calabria — fruity, oily, moderately hot. Different from dried flakes.",
    note:"Thin layer before sauce or on bianca — adds slow heat",
    qty:{ unit:"jar (200g)", yield_g:200, per_pizza_g:10, per_pizza_oz:0.4, per_pizza_tbsp:0.5, shared_yield:20, pantry:true, min_purchase:1 },
  },

  // ══ SAUCE ═══════════════════════════════════════════════════
  {
    id:"san_marzano", name:"San Marzano tomato",
    layer:"sauce", cuisine:["neapolitan","greek","levantine","turkish","northafrican","american","mexican"],
    profile:"T", sauceFamilies:["tomato"],
    stores:["sara","cm"],
    flavorNotes:["acid","umami","sweet"], moisture:"medium", weight:"light", presence:"anchor",
    note:"Crushed, uncooked, salt only — the universal anchor",
    qty:{ unit:"can (400g)", yield_g:400, per_pizza_g:75, per_pizza_oz:2.6, shared_yield:5, min_purchase:1 },
  },
  {
    id:"shakshuka_sauce", name:"Shakshuka sauce (jarred)",
    layer:"sauce", cuisine:["northafrican","levantine"],
    profile:"E", sauceFamilies:["tomato"],
    stores:["sara"], jarred:true, brand:"Mina or Wild Garden",
    flavorNotes:["acid","spice","umami"], moisture:"medium", weight:"light", presence:"anchor",
    desc:"Spiced North African tomato sauce with peppers and cumin — sold jarred at Sara's.",
    note:"Reduce in pan 5 min before using — tighten the sauce",
    qty:{ unit:"jar (450g)", yield_g:450, per_pizza_g:75, per_pizza_oz:2.6, shared_yield:6, min_purchase:1 },
  },
  {
    id:"pesto", name:"Pesto (basil)",
    layer:"sauce", cuisine:["neapolitan","american","greek"],
    profile:"T", sauceFamilies:["herb","nosause"],
    stores:["sara","cm"],
    flavorNotes:["herb","fat","umami"], moisture:"medium", weight:"medium", presence:"anchor",
    note:"Use as white sauce alternative — spread thin, don't over-apply",
    qty:{ unit:"jar (170g)", yield_g:170, per_pizza_g:40, per_pizza_oz:1.4, shared_yield:4, min_purchase:1 },
  },
  {
    id:"white_sauce", name:"Béchamel / cream base",
    layer:"sauce", cuisine:["neapolitan","american","greek"],
    profile:"T", sauceFamilies:["dairy"],
    stores:["cm"],
    flavorNotes:["cream","fat"], moisture:"medium", weight:"medium", presence:"anchor",
    note:"White pie — keep thin, season well. Make fresh.",
    qty:{ unit:"make fresh", yield_g:0, per_pizza_g:60, per_pizza_oz:2.1, min_purchase:1 },
  },
  {
    id:"labneh_sauce", name:"Labneh spread",
    layer:"sauce", cuisine:["levantine","turkish","greek","northafrican"],
    profile:"E", sauceFamilies:["dairy"],
    stores:["sara"],
    flavorNotes:["acid","cream","fat"], moisture:"low", weight:"medium", presence:"anchor",
    desc:"Strained yogurt cheese — thick, tangy, creamy. Middle Eastern staple. Replaces tomato entirely.",
    note:"Tangy, thick — classic bianca base for Levantine pies",
    qty:{ unit:"tub (500g)", yield_g:500, per_pizza_g:80, per_pizza_oz:2.8, shared_yield:6, min_purchase:1 },
  },
  {
    id:"tzatziki_sauce", name:"Tzatziki",
    layer:"sauce", cuisine:["greek","levantine","turkish"],
    profile:"T", sauceFamilies:["dairy"],
    stores:["sara","cm"],
    flavorNotes:["acid","cream","herb"], moisture:"medium", weight:"light", presence:"anchor",
    desc:"Greek yogurt with cucumber, garlic and dill — cooling, tangy dairy sauce.",
    note:"Use thick — drain cucumber well before making or buy ready-made",
    qty:{ unit:"tub (300g)", yield_g:300, per_pizza_g:70, per_pizza_oz:2.5, shared_yield:4, min_purchase:1 },
  },
  {
    id:"muhammara", name:"Muhammara",
    layer:"sauce", cuisine:["levantine","northafrican","turkish"],
    profile:"E", sauceFamilies:["spicepaste","herb"],
    stores:["sara"],
    flavorNotes:["sweet","smoke","spice","umami"], moisture:"low", weight:"medium", presence:"anchor",
    desc:"Syrian roasted red pepper and walnut spread — sweet, smoky, slightly spicy. A Levantine gem.",
    note:"Spread directly on dough — no extra sauce needed",
    qty:{ unit:"jar or fresh (200g)", yield_g:200, per_pizza_g:60, per_pizza_oz:2.1, shared_yield:3, min_purchase:1 },
  },
  {
    id:"chermoula", name:"Chermoula sauce",
    layer:"sauce", cuisine:["northafrican","levantine"],
    profile:"E", sauceFamilies:["herb"],
    stores:["sara"],
    flavorNotes:["herb","acid","spice"], moisture:"low", weight:"light", presence:"anchor",
    desc:"North African herb marinade — parsley, cilantro, cumin, lemon. Similar to chimichurri but warmer.",
    note:"Spread thin — herb-forward and lemony",
    qty:{ unit:"jar or fresh (200g)", yield_g:200, per_pizza_g:50, per_pizza_oz:1.8, shared_yield:4, min_purchase:1 },
  },
  {
    id:"biber_salcasi", name:"Biber salçası (Turkish pepper paste)",
    layer:"sauce", cuisine:["turkish","levantine"],
    profile:"E", sauceFamilies:["spicepaste","tomato"],
    stores:["sara"],
    flavorNotes:["sweet","smoke","umami","spice"], moisture:"low", weight:"medium", presence:"anchor",
    desc:"Turkish roasted red pepper paste — deeper and earthier than harissa, less heat, rich umami.",
    note:"Thin layer — mix with olive oil before spreading",
    qty:{ unit:"jar (400g)", yield_g:400, per_pizza_g:50, per_pizza_oz:1.8, shared_yield:8, pantry:true, min_purchase:1 },
  },
  {
    id:"tikka_sauce", name:"Tikka masala sauce",
    layer:"sauce", cuisine:["indian"],
    profile:"T", sauceFamilies:["spicepaste"],
    stores:["cm"],
    flavorNotes:["spice","cream","umami","acid"], moisture:"medium", weight:"medium", presence:"anchor",
    desc:"Creamy tomato-based Indian sauce with garam masala, ginger, garlic — bold and aromatic.",
    note:"Reduce until thick before applying — never watery",
    qty:{ unit:"jar (350g)", yield_g:350, per_pizza_g:75, per_pizza_oz:2.6, shared_yield:4, min_purchase:1 },
  },
  {
    id:"makhani_sauce", name:"Makhani (butter masala) sauce",
    layer:"sauce", cuisine:["indian"],
    profile:"E", sauceFamilies:["spicepaste","dairy"],
    stores:["cm"],
    flavorNotes:["cream","spice","fat","umami"], moisture:"medium", weight:"medium", presence:"anchor",
    desc:"Richer, creamier Indian sauce than tikka — butter-forward with gentle spice.",
    note:"Reduce before use — richer than tikka, pairs with paneer",
    qty:{ unit:"jar (350g)", yield_g:350, per_pizza_g:75, per_pizza_oz:2.6, shared_yield:4, min_purchase:1 },
  },
  {
    id:"tomatillo_sauce", name:"Tomatillo salsa verde",
    layer:"sauce", cuisine:["mexican"],
    profile:"T", sauceFamilies:["tomato"],
    stores:["cm"],
    flavorNotes:["acid","fresh","spice"], moisture:"medium", weight:"light", presence:"anchor",
    desc:"Charred green tomatillo sauce — tangy, bright, distinctly Mexican.",
    note:"Mexican hard lock — char and reduce before using",
    qty:{ unit:"jar (450g)", yield_g:450, per_pizza_g:75, per_pizza_oz:2.6, shared_yield:6, min_purchase:1 },
  },
  {
    id:"roja_sauce", name:"Charred tomato roja",
    layer:"sauce", cuisine:["mexican"],
    profile:"E", sauceFamilies:["tomato","spicepaste"],
    stores:["cm"],
    flavorNotes:["smoke","acid","spice","umami"], moisture:"medium", weight:"light", presence:"anchor",
    desc:"Ancho chili and charred tomato sauce — smoky, deep, distinctly Mexican.",
    note:"Mexican hard lock — smoky depth, reduce well",
    qty:{ unit:"jar (450g)", yield_g:450, per_pizza_g:75, per_pizza_oz:2.6, shared_yield:6, min_purchase:1 },
  },
  {
    id:"hummus_sauce", name:"Hummus spread",
    layer:"sauce", cuisine:["levantine","northafrican","greek"],
    profile:"T", sauceFamilies:["dairy"],
    stores:["sara","cm"],
    flavorNotes:["umami","fat","cream"], moisture:"low", weight:"medium", presence:"anchor",
    desc:"Chickpea and tahini puree — earthy, nutty, creamy. Use thin or it overwhelms.",
    note:"Thin layer only — too heavy if over-applied",
    qty:{ unit:"tub (400g)", yield_g:400, per_pizza_g:60, per_pizza_oz:2.1, shared_yield:6, min_purchase:1 },
  },
  {
    id:"lahmajun_spread", name:"Lahmajun meat spread",
    layer:"sauce", cuisine:["turkish","levantine"],
    profile:"E", sauceFamilies:["meatbase"],
    stores:["sara"], prep:PREP.RAW,
    flavorNotes:["spice","umami","heat","acid"], moisture:"low", weight:"heavy", presence:"anchor",
    desc:"Raw spiced lamb or beef mixed with tomato, parsley, peppers and Aleppo — spread thin on dough and baked directly. No cheese traditionally.",
    note:"Spread thin on raw dough — cooks with pizza. No cheese traditionally.",
    qty:{ unit:"200g ground lamb/beef", yield_g:200, per_pizza_g:200, per_pizza_oz:7.1, min_purchase:1 },
  },
  {
    id:"nosause", name:"No sauce — bianca",
    layer:"sauce", cuisine:["neapolitan","greek","levantine","turkish","northafrican","indian","american","mexican"],
    profile:"T", sauceFamilies:["nosause"],
    stores:[],
    flavorNotes:[], moisture:"dry", weight:"light", presence:"anchor",
    note:"Relies on base oil and cheese — don't skip the base layer",
    qty:{ unit:"n/a", yield_g:0, per_pizza_g:0, per_pizza_oz:0, min_purchase:0 },
  },

  // ══ CHEESE ══════════════════════════════════════════════════
  {
    id:"fior_di_latte", name:"Fior di latte",
    layer:"cheese", cuisine:["neapolitan","greek","levantine","turkish","american"],
    profile:"T", sauceFamilies:["tomato","dairy","nosause"],
    stores:["sara","cm"],
    flavorNotes:["cream","fat"], moisture:"medium", weight:"medium", presence:"anchor",
    desc:"Fresh cow's milk mozzarella — the classic Neapolitan cheese. Lower moisture than bufala.",
    note:"Slice thin, pat dry — essential for clean bake",
    qty:{ unit:"ball (125g)", yield_g:125, per_pizza_g:100, per_pizza_oz:3.5, min_purchase:1 },
  },
  {
    id:"bufala", name:"Buffalo mozzarella",
    layer:"cheese", cuisine:["neapolitan"],
    profile:"E", sauceFamilies:["tomato","nosause"],
    stores:["cm"], postbake:true,
    flavorNotes:["cream","acid","fat"], moisture:"postbake", weight:"medium", presence:"anchor",
    desc:"Water buffalo milk mozzarella — richer, tangier and wetter than fior di latte. Always post-bake.",
    note:"Post-bake only — too wet for oven, tears beautifully when hot",
    qty:{ unit:"ball (125g)", yield_g:125, per_pizza_g:100, per_pizza_oz:3.5, min_purchase:1 },
  },
  {
    id:"burrata", name:"Burrata",
    layer:"cheese", cuisine:["neapolitan","greek","american"],
    profile:"E", sauceFamilies:["tomato","nosause","herb"],
    stores:["cm"], postbake:true,
    flavorNotes:["cream","fat","sweet"], moisture:"postbake", weight:"medium", presence:"anchor",
    desc:"Fresh mozzarella shell filled with cream and stracciatella — explosively creamy when torn open post-bake.",
    note:"Post-bake only — tear open on hot pizza, never bake",
    qty:{ unit:"ball (125g)", yield_g:125, per_pizza_g:100, per_pizza_oz:3.5, min_purchase:1 },
  },
  {
    id:"fresh_mozz", name:"Fresh mozzarella",
    layer:"cheese", cuisine:["neapolitan","american","greek","levantine","turkish"],
    profile:"T", sauceFamilies:["tomato","dairy","nosause","herb"],
    stores:["sara","cm"],
    flavorNotes:["cream","fat"], moisture:"medium", weight:"medium", presence:"anchor",
    note:"Pat dry, slice — reliable everyday pizza cheese",
    qty:{ unit:"ball (125g)", yield_g:125, per_pizza_g:100, per_pizza_oz:3.5, min_purchase:1 },
  },
  {
    id:"shredded_mozz", name:"Shredded low-moisture mozz",
    layer:"cheese", cuisine:["american","neapolitan"],
    profile:"T", sauceFamilies:["tomato","spicepaste","dairy"],
    stores:["sara","cm"],
    flavorNotes:["cream","fat"], moisture:"low", weight:"medium", presence:"anchor",
    note:"Better melt and coverage for American style builds",
    qty:{ unit:"bag (225g)", yield_g:225, per_pizza_g:100, per_pizza_oz:3.5, shared_yield:2, min_purchase:1 },
  },
  {
    id:"gorgonzola", name:"Gorgonzola (crumbled)",
    layer:"cheese", cuisine:["neapolitan","american"],
    profile:"E", sauceFamilies:["nosause","dairy","tomato"],
    stores:["cm"],
    flavorNotes:["brine","umami","fat","acid"], moisture:"low", weight:"medium", presence:"anchor",
    desc:"Italian blue cheese — sharp, funky, creamy. Classic quattro formaggi component. Use sparingly.",
    note:"Strong — small amounts, pairs beautifully with hot honey or walnuts",
    qty:{ unit:"wedge (150g)", yield_g:150, per_pizza_g:40, per_pizza_oz:1.4, shared_yield:3, min_purchase:1 },
  },
  {
    id:"fontina", name:"Fontina",
    layer:"cheese", cuisine:["neapolitan","american"],
    profile:"T", sauceFamilies:["tomato","dairy","nosause"],
    stores:["cm"],
    flavorNotes:["cream","fat","umami"], moisture:"medium", weight:"medium", presence:"anchor",
    desc:"Northern Italian semi-soft cheese — buttery, nutty, exceptional melt. Quattro formaggi essential.",
    note:"Excellent melt — layer under or blend with mozz",
    qty:{ unit:"wedge (200g)", yield_g:200, per_pizza_g:80, per_pizza_oz:2.8, shared_yield:2, min_purchase:1 },
  },
  {
    id:"feta", name:"Feta (crumbled)",
    layer:"cheese", cuisine:["greek","levantine","turkish","northafrican","neapolitan"],
    profile:"T", sauceFamilies:["tomato","dairy","herb","nosause"],
    stores:["sara","cm"],
    flavorNotes:["brine","acid","fat"], moisture:"low", weight:"light", presence:"supporting",
    desc:"Brined Greek sheep's milk cheese — salty, tangy, crumbly. Doesn't melt, adds bursts of flavor.",
    note:"Add last 90 seconds or fully post-bake — oversalts if overbaked",
    qty:{ unit:"block (200g)", yield_g:200, per_pizza_g:40, per_pizza_oz:1.4, shared_yield:5, min_purchase:1 },
  },
  {
    id:"halloumi", name:"Halloumi (sliced)",
    layer:"cheese", cuisine:["greek","levantine","turkish"],
    profile:"E", sauceFamilies:["tomato","dairy","herb","nosause"],
    stores:["sara","cm"],
    flavorNotes:["brine","fat","umami"], moisture:"low", weight:"medium", presence:"anchor",
    desc:"Cypriot cheese with very high melting point — golden and squeaky when seared. Holds shape in oven.",
    note:"Pre-sear in dry pan until golden — holds shape perfectly",
    qty:{ unit:"block (225g)", yield_g:225, per_pizza_g:100, per_pizza_oz:3.5, shared_yield:2, min_purchase:1 },
  },
  {
    id:"kashkaval", name:"Kashkaval",
    layer:"cheese", cuisine:["turkish","levantine","greek","northafrican"],
    profile:"E", sauceFamilies:["tomato","dairy","spicepaste","herb","nosause"],
    stores:["sara","altin"],
    flavorNotes:["fat","umami","cream"], moisture:"low", weight:"medium", presence:"anchor",
    desc:"Balkan semi-hard cheese — excellent melt, mild and buttery. Turkey's answer to mozzarella.",
    note:"Grate or slice thin — superior melt for Turkish and Levantine pies",
    qty:{ unit:"block (200g)", yield_g:200, per_pizza_g:90, per_pizza_oz:3.2, shared_yield:2, min_purchase:1 },
  },
  {
    id:"shanklish", name:"Shanklish (crumbled)",
    layer:"cheese", cuisine:["levantine","turkish"],
    profile:"C", sauceFamilies:["tomato","herb","nosause"],
    stores:["sara"],
    flavorNotes:["brine","spice","umami","acid"], moisture:"dry", weight:"light", presence:"supporting",
    desc:"Aged, spiced Levantine cheese ball rolled in dried herbs and chili — pungent, earthy, distinctive.",
    note:"Crumble sparingly — very strong flavor, post-bake or last 60 seconds",
    qty:{ unit:"ball (150g)", yield_g:150, per_pizza_g:30, per_pizza_oz:1.1, shared_yield:5, min_purchase:1 },
  },
  {
    id:"goat_cheese", name:"Goat cheese (chèvre)",
    layer:"cheese", cuisine:["northafrican","american","greek","neapolitan"],
    profile:"E", sauceFamilies:["herb","nosause","tomato","dairy"],
    stores:["cm"],
    flavorNotes:["acid","cream","fat"], moisture:"low", weight:"light", presence:"supporting",
    desc:"Fresh soft goat cheese — tangy, creamy, lighter than ricotta. Dollop rather than spread.",
    note:"Dollop in rounds — pairs with beet, honey, arugula",
    qty:{ unit:"log (150g)", yield_g:150, per_pizza_g:50, per_pizza_oz:1.8, shared_yield:3, min_purchase:1 },
  },
  {
    id:"cotija", name:"Cotija (crumbled)",
    layer:"cheese", cuisine:["mexican"],
    profile:"T", sauceFamilies:["tomato","spicepaste"],
    stores:["cm"], postbake:true,
    flavorNotes:["brine","acid"], moisture:"postbake", weight:"light", presence:"supporting",
    desc:"Mexican aged crumbly cheese — salty and dry, similar to Parmigiano but sharper. Does not melt.",
    note:"Post-bake only — salty crumble finish",
    qty:{ unit:"wedge (200g)", yield_g:200, per_pizza_g:30, per_pizza_oz:1.1, shared_yield:6, min_purchase:1 },
  },
  {
    id:"paneer", name:"Paneer (cubed, spiced)",
    layer:"cheese", cuisine:["indian"],
    profile:"T", sauceFamilies:["spicepaste","dairy"],
    stores:["cm"],
    flavorNotes:["fat","cream","spice"], moisture:"low", weight:"medium", presence:"anchor",
    desc:"Indian fresh cheese — firm, mild, doesn't melt. Marinated and pre-cooked before adding to pizza.",
    note:"Marinate in tikka spices + yogurt min 30 min, then pan-sear",
    qty:{ unit:"block (200g)", yield_g:200, per_pizza_g:80, per_pizza_oz:2.8, min_purchase:1 },
  },
  {
    id:"aged_cheddar", name:"Aged cheddar",
    layer:"cheese", cuisine:["american"],
    profile:"T", sauceFamilies:["tomato","spicepaste"],
    stores:["cm"],
    flavorNotes:["fat","umami","acid"], moisture:"low", weight:"medium", presence:"supporting",
    note:"Sharp — always blend with mozz, never solo on pizza",
    qty:{ unit:"block (200g)", yield_g:200, per_pizza_g:50, per_pizza_oz:1.8, shared_yield:4, min_purchase:1 },
  },
  {
    id:"provolone", name:"Provolone (sharp)",
    layer:"cheese", cuisine:["neapolitan","american"],
    profile:"E", sauceFamilies:["tomato","dairy"],
    stores:["cm"],
    flavorNotes:["fat","umami","smoke"], moisture:"low", weight:"medium", presence:"supporting",
    desc:"Sharp Italian semi-hard cheese — slightly smoky, funky. Layer under mozz for depth.",
    note:"Layer under mozz — adds background funk",
    qty:{ unit:"block (150g)", yield_g:150, per_pizza_g:50, per_pizza_oz:1.8, shared_yield:3, min_purchase:1 },
  },
  {
    id:"ricotta_dollop", name:"Ricotta (dolloped)",
    layer:"cheese", cuisine:["neapolitan","american","greek"],
    profile:"E", sauceFamilies:["tomato","dairy","nosause"],
    stores:["sara","cm"],
    flavorNotes:["cream","fat","sweet"], moisture:"medium", weight:"light", presence:"supporting",
    note:"Drop in spoonfuls — creamy pockets mid-bake",
    qty:{ unit:"tub (250g)", yield_g:250, per_pizza_g:60, per_pizza_oz:2.1, shared_yield:4, min_purchase:1 },
  },

  // ══ PROTEIN ═════════════════════════════════════════════════
  {
    id:"beef_kofta", name:"Spiced beef kofta",
    layer:"protein", cuisine:["turkish","levantine","northafrican","greek"],
    profile:"E", sauceFamilies:["tomato","dairy","spicepaste","herb"],
    stores:["sara"], prep:PREP.PRE,
    flavorNotes:["spice","umami","fat"], moisture:"low", weight:"heavy", presence:"anchor",
    note:"Par-cook before adding — crumble or slice thin",
    qty:{ unit:"300g ground beef", yield_g:300, per_pizza_g:90, per_pizza_oz:3.2, min_purchase:1 },
  },
  {
    id:"lamb_mince", name:"Spiced lamb mince",
    layer:"protein", cuisine:["turkish","greek","northafrican","levantine"],
    profile:"E", sauceFamilies:["tomato","dairy","spicepaste","herb"],
    stores:["sara"], prep:PREP.PRE,
    flavorNotes:["spice","umami","fat"], moisture:"low", weight:"heavy", presence:"anchor",
    note:"Season with cumin, allspice, Aleppo — par-cook, drain fat",
    qty:{ unit:"300g ground lamb", yield_g:300, per_pizza_g:90, per_pizza_oz:3.2, min_purchase:1 },
  },
  {
    id:"sujuk", name:"Sujuk (beef)",
    layer:"protein", cuisine:["turkish","levantine","northafrican"],
    profile:"E", sauceFamilies:["tomato","spicepaste","dairy"],
    stores:["sara","altin"], prep:PREP.READY,
    flavorNotes:["spice","fat","smoke","umami"], moisture:"low", weight:"medium", presence:"anchor",
    desc:"Turkish/Levantine dry-cured spiced beef sausage — garlic, cumin, fenugreek. Several brands at Sara's and Altin.",
    note:"Slice thin — renders fat beautifully in Dome, crisps at edges",
    qty:{ unit:"link (200g)", yield_g:200, per_pizza_g:80, per_pizza_oz:2.8, shared_yield:2, min_purchase:1 },
  },
  {
    id:"basturma", name:"Basturma (beef)",
    layer:"protein", cuisine:["turkish","levantine"],
    profile:"C", sauceFamilies:["tomato","spicepaste","nosause"],
    stores:["sara"], prep:PREP.READY,
    flavorNotes:["spice","umami","fat","smoke"], moisture:"dry", weight:"light", presence:"supporting",
    desc:"Air-dried cured beef coated in thick fenugreek-spice paste (çemen) — intensely flavored, very aromatic.",
    note:"Slice paper-thin — very strong flavor, use sparingly. Pairs with egg.",
    qty:{ unit:"pack (150g)", yield_g:150, per_pizza_g:40, per_pizza_oz:1.4, shared_yield:3, min_purchase:1 },
  },
  {
    id:"anchovy", name:"Anchovy (oil-packed)",
    layer:"protein", cuisine:["neapolitan","greek","levantine"],
    profile:"E", sauceFamilies:["tomato","herb","nosause"],
    stores:["cm"], prep:PREP.READY,
    flavorNotes:["brine","umami","fat"], moisture:"low", weight:"light", presence:"supporting",
    desc:"Salt-cured fish fillets in olive oil — intensely savory and umami. A Neapolitan staple.",
    note:"Add last 60 seconds — use 3–4 fillets max, they dissolve into the pie",
    qty:{ unit:"tin (50g)", yield_g:50, per_pizza_g:20, per_pizza_oz:0.7, shared_yield:2, min_purchase:1 },
  },
  {
    id:"chicken_tikka", name:"Chicken tikka (pre-cooked)",
    layer:"protein", cuisine:["indian"],
    profile:"T", sauceFamilies:["spicepaste","dairy"],
    stores:["sara"], prep:PREP.PRE,
    flavorNotes:["spice","umami","smoke"], moisture:"low", weight:"medium", presence:"anchor",
    note:"⚠️ Poultry — fully cooked before pizza. Marinate overnight in yogurt and spices.",
    qty:{ unit:"300g chicken breast", yield_g:300, per_pizza_g:90, per_pizza_oz:3.2, min_purchase:1 },
  },
  {
    id:"chicken_tandoori", name:"Chicken tandoori (pre-cooked)",
    layer:"protein", cuisine:["indian"],
    profile:"E", sauceFamilies:["spicepaste","dairy"],
    stores:["sara"], prep:PREP.PRE,
    flavorNotes:["spice","smoke","umami"], moisture:"low", weight:"medium", presence:"anchor",
    desc:"Tandoori marinade is drier and smokier than tikka — yogurt, Kashmiri chili, cumin, charred finish.",
    note:"⚠️ Poultry — fully cooked. Slice thin off the bone before adding.",
    qty:{ unit:"300g chicken thighs", yield_g:300, per_pizza_g:90, per_pizza_oz:3.2, min_purchase:1 },
  },
  {
    id:"chicken_bbq", name:"BBQ chicken (shredded)",
    layer:"protein", cuisine:["american"],
    profile:"T", sauceFamilies:["tomato","spicepaste"],
    stores:["cm"], prep:PREP.PRE,
    flavorNotes:["smoke","sweet","umami"], moisture:"medium", weight:"medium", presence:"anchor",
    note:"⚠️ Poultry — fully cooked, sauced, then added",
    qty:{ unit:"300g chicken thighs", yield_g:300, per_pizza_g:90, per_pizza_oz:3.2, min_purchase:1 },
  },
  {
    id:"beef_pepperoni", name:"Beef pepperoni",
    layer:"protein", cuisine:["american","neapolitan"],
    profile:"T", sauceFamilies:["tomato","spicepaste"],
    stores:["sara","cm"], prep:PREP.READY,
    flavorNotes:["spice","fat","umami","smoke"], moisture:"low", weight:"medium", presence:"anchor",
    note:"Halal beef pepperoni — cups and crisps beautifully at Dome temp",
    qty:{ unit:"pack (150g)", yield_g:150, per_pizza_g:60, per_pizza_oz:2.1, shared_yield:2, min_purchase:1 },
  },
  {
    id:"beef_salami", name:"Beef salami",
    layer:"protein", cuisine:["american","neapolitan"],
    profile:"T", sauceFamilies:["tomato","dairy","nosause"],
    stores:["sara","cm"], prep:PREP.READY,
    flavorNotes:["fat","umami","spice"], moisture:"low", weight:"medium", presence:"anchor",
    desc:"Halal beef salami — milder and more delicate than pepperoni. Sliced thin.",
    note:"Slice thin — place flat, crisps at edges in Dome",
    qty:{ unit:"pack (150g)", yield_g:150, per_pizza_g:60, per_pizza_oz:2.1, shared_yield:2, min_purchase:1 },
  },
  {
    id:"beef_diavola", name:"Beef diavola salami",
    layer:"protein", cuisine:["neapolitan","american"],
    profile:"E", sauceFamilies:["tomato","spicepaste"],
    stores:["cm"], prep:PREP.READY,
    flavorNotes:["heat","fat","spice","umami"], moisture:"low", weight:"medium", presence:"anchor",
    desc:"Spicy beef salami — hotter and more aggressively seasoned than regular salami.",
    note:"Slice thin — intense heat, pairs with honey or cream cheese to balance",
    qty:{ unit:"pack (150g)", yield_g:150, per_pizza_g:60, per_pizza_oz:2.1, shared_yield:2, min_purchase:1 },
  },
  {
    id:"bresaola", name:"Bresaola (beef)",
    layer:"protein", cuisine:["neapolitan","american","greek"],
    profile:"E", sauceFamilies:["nosause","dairy","herb","tomato"],
    stores:["cm"], prep:PREP.READY, postbake:true,
    flavorNotes:["umami","brine","acid"], moisture:"postbake", weight:"light", presence:"supporting",
    desc:"Italian air-dried salted beef — lean, delicate, deep red. Always post-bake. Classic with arugula and Parmigiano.",
    note:"Post-bake only — drape over hot pizza, pairs with arugula and lemon",
    qty:{ unit:"pack (100g)", yield_g:100, per_pizza_g:60, per_pizza_oz:2.1, shared_yield:1, min_purchase:1 },
  },
  {
    id:"chicken_shawarma", name:"Chicken shawarma strips",
    layer:"protein", cuisine:["levantine","turkish","northafrican"],
    profile:"T", sauceFamilies:["tomato","dairy","herb","spicepaste"],
    stores:["sara"], prep:PREP.PRE,
    flavorNotes:["spice","umami","smoke"], moisture:"low", weight:"medium", presence:"anchor",
    desc:"Middle Eastern spiced rotisserie chicken — available pre-cooked from Sara's deli fridge.",
    note:"⚠️ Poultry — Sara's deli fridge has pre-cooked. Slice and warm before adding.",
    qty:{ unit:"300g or pre-cooked from Sara's deli fridge", yield_g:300, per_pizza_g:90, per_pizza_oz:3.2, min_purchase:1 },
  },
  {
    id:"lamb_merguez", name:"Lamb merguez (sliced)",
    layer:"protein", cuisine:["northafrican","levantine"],
    profile:"E", sauceFamilies:["tomato","spicepaste","herb"],
    stores:["sara"], prep:PREP.PRE,
    flavorNotes:["heat","spice","fat","umami"], moisture:"low", weight:"medium", presence:"anchor",
    desc:"Spicy North African lamb sausage — red from paprika, harissa and chili.",
    note:"Par-cook, slice on bias — fiery and aromatic",
    qty:{ unit:"pack (200g)", yield_g:200, per_pizza_g:80, per_pizza_oz:2.8, shared_yield:2, min_purchase:1 },
  },
  {
    id:"carne_asada", name:"Carne asada (sliced)",
    layer:"protein", cuisine:["mexican"],
    profile:"T", sauceFamilies:["tomato","spicepaste"],
    stores:["cm"], prep:PREP.PRE,
    flavorNotes:["umami","smoke","acid"], moisture:"low", weight:"medium", presence:"anchor",
    note:"Fully cooked before adding — thin slices, season with lime and cumin",
    qty:{ unit:"300g skirt steak", yield_g:300, per_pizza_g:90, per_pizza_oz:3.2, min_purchase:1 },
  },
  {
    id:"beef_chorizo", name:"Beef chorizo",
    layer:"protein", cuisine:["mexican","american"],
    profile:"T", sauceFamilies:["tomato","spicepaste"],
    stores:["cm"], prep:PREP.PRE,
    flavorNotes:["spice","fat","smoke","umami"], moisture:"low", weight:"medium", presence:"anchor",
    note:"Render in pan, drain fat — crumble over pizza",
    qty:{ unit:"pack (225g)", yield_g:225, per_pizza_g:80, per_pizza_oz:2.8, shared_yield:2, min_purchase:1 },
  },
  {
    id:"beef_meatballs", name:"Beef meatballs (sliced)",
    layer:"protein", cuisine:["neapolitan","american"],
    profile:"T", sauceFamilies:["tomato","dairy"],
    stores:["sara","cm"], prep:PREP.PRE,
    flavorNotes:["umami","fat","spice"], moisture:"medium", weight:"heavy", presence:"anchor",
    note:"Pre-cook fully, slice in half — classic American-Neapolitan combination",
    qty:{ unit:"300g ground beef", yield_g:300, per_pizza_g:90, per_pizza_oz:3.2, min_purchase:1 },
  },
  {
    id:"egg", name:"Egg (whole, cracked)",
    layer:"protein", cuisine:["neapolitan","turkish","levantine","northafrican"],
    profile:"E", sauceFamilies:["tomato","dairy","herb","nosause","spicepaste"],
    stores:["sara"], prep:PREP.RAW,
    flavorNotes:["fat","cream","umami"], moisture:"medium", weight:"light", presence:"supporting",
    note:"Dome: crack in last 20s — runny yolk. Steel: add at 3-min mark, yolk sets more.",
    qty:{ unit:"eggs", yield_g:60, per_pizza_g:60, per_pizza_oz:2.1, per_pizza_unit:1, min_purchase:6 },
  },
  {
    id:"labneh_balls", name:"Labneh balls (marinated)",
    layer:"protein", cuisine:["levantine","northafrican"],
    profile:"C", sauceFamilies:["dairy","herb","nosause"],
    stores:["sara"], prep:PREP.READY, postbake:true,
    flavorNotes:["acid","cream","herb"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Labneh rolled into balls and preserved in olive oil with herbs — tangy, creamy, beautiful post-bake.",
    note:"Post-bake only — tear and scatter over hot pizza",
    qty:{ unit:"jar (300g)", yield_g:300, per_pizza_g:60, per_pizza_oz:2.1, shared_yield:5, min_purchase:1 },
  },
  {
    id:"nduja_homemade", name:"Homemade Beef Nduja",
    layer:"protein", cuisine:["neapolitan","american"],
    profile:"E", sauceFamilies:["tomato","spicepaste","nosause"],
    stores:["sara"], prep:PREP.PRE, homemade:true,
    make_ahead:true, make_ahead_timing:"day before",
    flavorNotes:["heat","fat","spice","smoke","umami"], moisture:"low", weight:"medium", presence:"anchor",
    desc:"Beef version of Calabrian spreadable chili sausage — made from sujuk rendered with EVOO and Aleppo pepper.",
    note:"Make ahead — spread thin on dough before or after sauce.",
    recipe:{
      makes:"enough for 3–4 pizzas",
      ingredients:[
        "2–3 sujuk links, casing removed (Sara's or Altin)",
        "4 tbsp high-quality EVOO",
        "1 tsp Aleppo pepper (or Isot biber for smokier result)",
        "½ tsp smoked paprika",
        "1 small roasted red pepper (optional — adds body)",
      ],
      method:[
        "Remove casing from sujuk and break meat into a cold dry pan.",
        "Render on medium heat until fat releases and meat is fully cooked, about 8 minutes.",
        "Transfer to a small food processor or mortar. Add EVOO, Aleppo pepper and smoked paprika.",
        "Blend or pound until a spreadable paste forms — rough texture is fine.",
        "Stir in roasted red pepper if using. Taste and adjust heat.",
        "Store in a jar covered with EVOO. Refrigerates for up to 1 week.",
        "Use: spread thin on raw dough before sauce, or dot post-bake with residual heat.",
      ]
    },
    qty:{ unit:"2–3 sujuk links from Sara's or Altin", yield_g:200, per_pizza_g:40, per_pizza_oz:1.4, min_purchase:1 },
  },

  // ══ VEG ═════════════════════════════════════════════════════
  {
    id:"cherry_tom", name:"Cherry tomatoes (halved)",
    layer:"veg", cuisine:["neapolitan","greek","american","levantine","turkish","northafrican"],
    profile:"T", sauceFamilies:["tomato","dairy","herb","nosause"],
    stores:["sara","cm"],
    flavorNotes:["acid","sweet","fresh"], moisture:"high", weight:"light", presence:"supporting",
    note:"Universal — high moisture, don't overload",
    qty:{ unit:"punnet (250g)", yield_g:250, per_pizza_g:50, per_pizza_oz:1.8, shared_yield:5, min_purchase:1 },
  },
  {
    id:"roasted_peppers", name:"Roasted red peppers",
    layer:"veg", cuisine:["turkish","greek","northafrican","american","levantine"],
    profile:"T", sauceFamilies:["tomato","dairy","spicepaste","herb"],
    stores:["sara","cm"],
    flavorNotes:["sweet","smoke","acid"], moisture:"medium", weight:"light", presence:"supporting",
    note:"Pat dry if jarred — excess brine ruins the base",
    qty:{ unit:"jar (290g)", yield_g:200, per_pizza_g:50, per_pizza_oz:1.8, shared_yield:4, min_purchase:1 },
  },
  {
    id:"kalamata", name:"Kalamata olives",
    layer:"veg", cuisine:["greek","levantine","neapolitan","northafrican"],
    profile:"T", sauceFamilies:["tomato","dairy","herb","nosause"],
    stores:["sara","cm"],
    flavorNotes:["brine","fat","acid"], moisture:"low", weight:"light", presence:"accent",
    note:"Pit and halve — strong brine flavor",
    qty:{ unit:"jar (350g)", yield_g:200, per_pizza_g:30, per_pizza_oz:1.1, shared_yield:6, min_purchase:1 },
  },
  {
    id:"green_olives", name:"Castelvetrano olives",
    layer:"veg", cuisine:["neapolitan","northafrican","greek"],
    profile:"E", sauceFamilies:["tomato","dairy","herb","nosause"],
    stores:["cm"],
    flavorNotes:["fat","sweet","brine"], moisture:"low", weight:"light", presence:"accent",
    desc:"Sicilian buttery green olive — mild, meaty, nothing like a regular green olive.",
    note:"Pit and halve — buttery and mild",
    qty:{ unit:"jar (290g)", yield_g:180, per_pizza_g:30, per_pizza_oz:1.1, shared_yield:6, min_purchase:1 },
  },
  {
    id:"artichoke", name:"Artichoke hearts",
    layer:"veg", cuisine:["neapolitan","greek","levantine"],
    profile:"E", sauceFamilies:["tomato","dairy","nosause","herb"],
    stores:["sara","cm"],
    flavorNotes:["umami","acid","sweet"], moisture:"medium", weight:"medium", presence:"supporting",
    note:"Pat dry, quarter — use jarred in water not oil",
    qty:{ unit:"can (400g)", yield_g:200, per_pizza_g:50, per_pizza_oz:1.8, shared_yield:4, min_purchase:1 },
  },
  {
    id:"capers", name:"Capers",
    layer:"veg", cuisine:["neapolitan","greek","levantine"],
    profile:"E", sauceFamilies:["tomato","herb","nosause","dairy"],
    stores:["sara","cm"],
    flavorNotes:["brine","acid"], moisture:"low", weight:"light", presence:"accent",
    desc:"Pickled flower buds — briny, pungent, intensely savory. A Neapolitan staple.",
    note:"Rinse before using — salt-packed are best if available",
    qty:{ unit:"jar (100g)", yield_g:100, per_pizza_g:15, per_pizza_oz:0.5, shared_yield:6, pantry:true, min_purchase:1 },
  },
  {
    id:"caramelized_onion", name:"Caramelized onions",
    layer:"veg", cuisine:["turkish","american","greek","levantine","northafrican"],
    profile:"T", sauceFamilies:["tomato","dairy","spicepaste","nosause"],
    stores:["sara","cm"],
    flavorNotes:["sweet","umami","fat"], moisture:"medium", weight:"light", presence:"supporting",
    note:"Cook fully before adding — minimum 30 minutes low heat",
    qty:{ unit:"onions", yield_g:200, per_pizza_g:60, per_pizza_oz:2.1, per_pizza_unit:0.5, min_purchase:2 },
  },
  {
    id:"red_onion", name:"Red onion (thin sliced)",
    layer:"veg", cuisine:["greek","indian","mexican","american","levantine"],
    profile:"T", sauceFamilies:["tomato","dairy","spicepaste","herb"],
    stores:["sara","cm"],
    flavorNotes:["acid","fresh","brine"], moisture:"low", weight:"light", presence:"accent",
    note:"Quick pickle for less bite — 10 min in lime juice",
    qty:{ unit:"onion", yield_g:150, per_pizza_g:30, per_pizza_oz:1.1, per_pizza_unit:0.25, min_purchase:1 },
  },
  {
    id:"jalapeno_fresh", name:"Jalapeño (fresh sliced)",
    layer:"veg", cuisine:["mexican","american"],
    profile:"T", sauceFamilies:["tomato","spicepaste"],
    stores:["cm"],
    flavorNotes:["heat","fresh","acid"], moisture:"medium", weight:"light", presence:"accent",
    note:"Seed for moderate heat, keep seeds for fire",
    qty:{ unit:"jalapeños", yield_g:60, per_pizza_g:20, per_pizza_oz:0.7, per_pizza_unit:0.5, min_purchase:2 },
  },
  {
    id:"jalapeno_pickled", name:"Pickled jalapeños",
    layer:"veg", cuisine:["mexican","american"],
    profile:"T", sauceFamilies:["tomato","spicepaste"],
    stores:["cm"], postbake:true,
    flavorNotes:["heat","acid","brine"], moisture:"postbake", weight:"light", presence:"accent",
    note:"Post-bake — preserves tang and crunch",
    qty:{ unit:"jar (300g)", yield_g:150, per_pizza_g:20, per_pizza_oz:0.7, shared_yield:7, pantry:true, min_purchase:1 },
  },
  {
    id:"pickled_cabbage", name:"Pickled red cabbage",
    layer:"veg", cuisine:["mexican","american"],
    profile:"E", sauceFamilies:["tomato","spicepaste"],
    stores:["cm"], postbake:true,
    flavorNotes:["acid","crunch","brine"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Vinegar-pickled shredded red cabbage — crunchy, tangy, vibrant purple color.",
    note:"Post-bake only — loses color and crunch in oven",
    qty:{ unit:"jar (300g)", yield_g:150, per_pizza_g:30, per_pizza_oz:1.1, shared_yield:5, pantry:true, min_purchase:1 },
  },
  {
    id:"corn_charred", name:"Charred corn",
    layer:"veg", cuisine:["mexican","american"],
    profile:"T", sauceFamilies:["tomato","spicepaste","dairy"],
    stores:["cm"],
    flavorNotes:["sweet","smoke","fresh"], moisture:"low", weight:"light", presence:"supporting",
    note:"Cast iron or open flame — never use canned without charring first",
    qty:{ unit:"ears of corn", yield_g:200, per_pizza_g:50, per_pizza_oz:1.8, per_pizza_unit:0.5, min_purchase:2 },
  },
  {
    id:"mushroom_cremini", name:"Cremini mushrooms",
    layer:"veg", cuisine:["neapolitan","american","turkish"],
    profile:"T", sauceFamilies:["tomato","dairy","nosause"],
    stores:["sara","cm"],
    flavorNotes:["umami","fat","sweet"], moisture:"high", weight:"medium", presence:"supporting",
    note:"Sauté first until golden — raw mushrooms steam and waterlog the base",
    qty:{ unit:"punnet (250g)", yield_g:250, per_pizza_g:60, per_pizza_oz:2.1, shared_yield:4, min_purchase:1 },
  },
  {
    id:"mushroom_wild", name:"Wild mushrooms (roasted)",
    layer:"veg", cuisine:["neapolitan"],
    profile:"C", sauceFamilies:["nosause","dairy","tomato"],
    stores:["cm"],
    flavorNotes:["umami","fat","smoke"], moisture:"medium", weight:"medium", presence:"anchor",
    desc:"Maitake, oyster or chanterelle — earthy, complex, nothing like cremini.",
    note:"Roast at 425°F with EVOO and thyme first — never add raw",
    qty:{ unit:"punnet (150g)", yield_g:150, per_pizza_g:60, per_pizza_oz:2.1, min_purchase:1 },
  },
  {
    id:"eggplant_roasted", name:"Roasted eggplant",
    layer:"veg", cuisine:["levantine","turkish","greek","northafrican"],
    profile:"E", sauceFamilies:["tomato","dairy","herb","spicepaste"],
    stores:["sara","cm"],
    flavorNotes:["umami","smoke","fat","sweet"], moisture:"medium", weight:"medium", presence:"supporting",
    note:"Salt, drain 20 min, roast — never add raw eggplant",
    qty:{ unit:"eggplant", yield_g:300, per_pizza_g:70, per_pizza_oz:2.5, per_pizza_unit:0.5, min_purchase:1 },
  },
  {
    id:"spinach", name:"Baby spinach (wilted)",
    layer:"veg", cuisine:["indian","levantine","greek","northafrican"],
    profile:"T", sauceFamilies:["tomato","dairy","spicepaste","herb","nosause"],
    stores:["sara","cm"],
    flavorNotes:["fresh","umami","herb"], moisture:"high", weight:"light", presence:"supporting",
    note:"Add 90 seconds before pulling — wilts perfectly",
    qty:{ unit:"bag (150g)", yield_g:150, per_pizza_g:30, per_pizza_oz:1.1, shared_yield:5, min_purchase:1 },
  },
  {
    id:"preserved_lemon", name:"Preserved lemon (rinsed)",
    layer:"veg", cuisine:["northafrican","levantine"],
    profile:"C", sauceFamilies:["tomato","herb","dairy"],
    stores:["sara"],
    flavorNotes:["acid","brine","fresh"], moisture:"low", weight:"light", presence:"accent",
    desc:"Salt-cured whole lemon — intensely lemony, salty, fermented flavor. Use the rind only, rinse well.",
    note:"Rinse thoroughly, use rind only — tiny amounts, very salty",
    qty:{ unit:"jar (200g)", yield_g:200, per_pizza_g:15, per_pizza_oz:0.5, shared_yield:13, pantry:true, min_purchase:1 },
  },
  {
    id:"potato_thin", name:"Thinly sliced potato",
    layer:"veg", cuisine:["neapolitan"],
    profile:"C", sauceFamilies:["nosause","dairy"],
    stores:["sara"],
    flavorNotes:["starch","fat","sweet"], moisture:"low", weight:"medium", presence:"anchor",
    note:"Classic Neapolitan bianca — slice paper thin or blanch first",
    qty:{ unit:"medium potatoes", yield_g:300, per_pizza_g:100, per_pizza_oz:3.5, per_pizza_unit:1, min_purchase:2 },
  },
  {
    id:"beet_roasted", name:"Roasted beet",
    layer:"veg", cuisine:["greek","northafrican"],
    profile:"C", sauceFamilies:["dairy","nosause","herb"],
    stores:["sara","cm"],
    flavorNotes:["sweet","acid","umami"], moisture:"medium", weight:"medium", presence:"supporting",
    note:"Pre-roast and slice thin — pairs with feta or goat cheese",
    qty:{ unit:"medium beets", yield_g:300, per_pizza_g:70, per_pizza_oz:2.5, per_pizza_unit:1, min_purchase:3 },
  },
  {
    id:"sun_dried_tom", name:"Sun-dried tomatoes",
    layer:"veg", cuisine:["neapolitan","greek","levantine"],
    profile:"E", sauceFamilies:["tomato","dairy","herb"],
    stores:["sara","cm"],
    flavorNotes:["umami","acid","sweet","fat"], moisture:"low", weight:"light", presence:"accent",
    note:"Drain from oil — intense, use sparingly",
    qty:{ unit:"jar (200g)", yield_g:150, per_pizza_g:30, per_pizza_oz:1.1, shared_yield:5, pantry:true, min_purchase:1 },
  },
  {
    id:"piquillo_peppers", name:"Piquillo peppers",
    layer:"veg", cuisine:["neapolitan","northafrican"],
    profile:"C", sauceFamilies:["tomato","dairy","spicepaste"],
    stores:["cm"],
    flavorNotes:["sweet","smoke","acid"], moisture:"medium", weight:"light", presence:"supporting",
    desc:"Spanish roasted sweet-smoky peppers — more intense than regular roasted peppers.",
    note:"Drain and pat dry",
    qty:{ unit:"jar (290g)", yield_g:180, per_pizza_g:50, per_pizza_oz:1.8, shared_yield:3, min_purchase:1 },
  },
  {
    id:"za_atar_onion", name:"Za'atar-roasted onion",
    layer:"veg", cuisine:["levantine","turkish","northafrican"],
    profile:"E", sauceFamilies:["tomato","dairy","herb","nosause"],
    stores:["sara"],
    flavorNotes:["herb","sweet","umami"], moisture:"medium", weight:"light", presence:"supporting",
    note:"Roast at 400°F with za'atar + olive oil first",
    qty:{ unit:"medium onions", yield_g:250, per_pizza_g:60, per_pizza_oz:2.1, per_pizza_unit:0.5, min_purchase:2 },
  },
  {
    id:"broccoli_rabe", name:"Broccoli rabe (rapini)",
    layer:"veg", cuisine:["neapolitan","american"],
    profile:"E", sauceFamilies:["tomato","dairy","nosause","herb"],
    stores:["cm"],
    flavorNotes:["herb","bitter","umami"], moisture:"medium", weight:"medium", presence:"supporting",
    desc:"Bitter Italian greens — not broccoli, more pungent and leafy. Blanch first to tame bitterness.",
    note:"Blanch 2 min in salted water, sauté with garlic and chili before adding",
    qty:{ unit:"bunch (250g)", yield_g:250, per_pizza_g:60, per_pizza_oz:2.1, shared_yield:4, min_purchase:1 },
  },
  {
    id:"zucchini_roasted", name:"Zucchini (roasted)",
    layer:"veg", cuisine:["neapolitan","greek","northafrican","levantine"],
    profile:"T", sauceFamilies:["tomato","dairy","herb","nosause"],
    stores:["sara","cm"],
    flavorNotes:["sweet","fresh","umami"], moisture:"medium", weight:"light", presence:"supporting",
    note:"Slice thin, roast at 400°F until edges brown — never raw on pizza",
    qty:{ unit:"medium zucchini", yield_g:200, per_pizza_g:60, per_pizza_oz:2.1, per_pizza_unit:0.5, min_purchase:1 },
  },
  {
    id:"fennel_roasted", name:"Fennel (shaved or roasted)",
    layer:"veg", cuisine:["neapolitan","northafrican"],
    profile:"E", sauceFamilies:["tomato","dairy","nosause","herb"],
    stores:["sara","cm"],
    flavorNotes:["sweet","herb","acid"], moisture:"medium", weight:"light", presence:"supporting",
    desc:"Anise-flavored bulb vegetable — sweet and aromatic when roasted, becomes mild and caramelized.",
    note:"Roast until caramelized or shave raw paper-thin for white pies",
    qty:{ unit:"fennel bulb", yield_g:200, per_pizza_g:60, per_pizza_oz:2.1, per_pizza_unit:0.5, min_purchase:1 },
  },
  {
    id:"roasted_garlic_cloves", name:"Roasted garlic cloves",
    layer:"veg", cuisine:["neapolitan","american","greek","levantine","turkish"],
    profile:"T", sauceFamilies:["tomato","dairy","nosause","herb","spicepaste"],
    stores:["sara","cm"],
    flavorNotes:["sweet","umami","fat"], moisture:"low", weight:"light", presence:"accent",
    note:"Roast whole head at 400°F for 40 min — cloves squeeze out sweet and jammy",
    qty:{ unit:"head of garlic", yield_g:50, per_pizza_g:15, per_pizza_oz:0.5, per_pizza_unit:0.25, min_purchase:1 },
  },
  {
    id:"dried_apricots", name:"Dried apricots (chopped)",
    layer:"veg", cuisine:["northafrican","turkish","levantine"],
    profile:"E", sauceFamilies:["spicepaste","herb","dairy"],
    stores:["sara","cm"],
    flavorNotes:["sweet","acid","fresh"], moisture:"low", weight:"light", presence:"accent",
    desc:"Moroccan sweet-savory tradition — chopped apricots add sweetness against spiced lamb or merguez.",
    note:"Chop small — sweet contrast against harissa or spiced meats only",
    qty:{ unit:"bag (200g)", yield_g:200, per_pizza_g:20, per_pizza_oz:0.7, shared_yield:10, pantry:true, min_purchase:1 },
  },
  {
    id:"cauliflower_roasted", name:"Cauliflower (roasted)",
    layer:"veg", cuisine:["indian","neapolitan","levantine"],
    profile:"E", sauceFamilies:["spicepaste","dairy","tomato","nosause"],
    stores:["sara","cm"],
    flavorNotes:["sweet","umami","starch"], moisture:"low", weight:"medium", presence:"supporting",
    note:"Roast at 425°F until deeply golden — season with cumin for Indian pies",
    qty:{ unit:"½ head cauliflower", yield_g:300, per_pizza_g:70, per_pizza_oz:2.5, min_purchase:1 },
  },
  {
    id:"green_pepper", name:"Green bell pepper",
    layer:"veg", cuisine:["american","mexican","turkish","levantine"],
    profile:"T", sauceFamilies:["tomato","spicepaste","dairy"],
    stores:["sara","cm"],
    flavorNotes:["fresh","bitter","acid"], moisture:"medium", weight:"light", presence:"supporting",
    note:"Slice thin — pre-roast for sweetness or use raw for crunch",
    qty:{ unit:"pepper", yield_g:150, per_pizza_g:40, per_pizza_oz:1.4, per_pizza_unit:0.3, min_purchase:1 },
  },
  {
    id:"crispy_onions", name:"Crispy fried onions",
    layer:"veg", cuisine:["american","turkish","levantine","indian"],
    profile:"T", sauceFamilies:["tomato","dairy","spicepaste","nosause"],
    stores:["cm"], postbake:true,
    flavorNotes:["sweet","crunch","fat"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Packaged fried onions — crunchy, savory, instant texture.",
    note:"Post-bake only — add just before serving to keep crunch",
    qty:{ unit:"can (100g)", yield_g:100, per_pizza_g:15, per_pizza_oz:0.5, shared_yield:6, pantry:true, min_purchase:1 },
  },
  {
    id:"pomegranate_arils", name:"Pomegranate arils",
    layer:"veg", cuisine:["levantine","turkish","northafrican","greek"],
    profile:"E", sauceFamilies:["dairy","herb","nosause","tomato"],
    stores:["sara","cm"], postbake:true,
    flavorNotes:["acid","sweet","fresh","crunch"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Fresh pomegranate seeds — burst of sweet-tart juice, jewel-like color.",
    note:"Post-bake only — scatter over finished pizza for color and acid pop",
    qty:{ unit:"pomegranate", yield_g:150, per_pizza_g:30, per_pizza_oz:1.1, per_pizza_unit:0.25, min_purchase:1 },
  },

  // ══ FINISH ══════════════════════════════════════════════════
  {
    id:"fresh_basil", name:"Fresh basil",
    layer:"finish", cuisine:["neapolitan","greek","american","levantine","turkish"],
    profile:"T", sauceFamilies:["tomato","dairy","herb","nosause"],
    stores:["sara","cm"], postbake:true,
    flavorNotes:["herb","fresh","sweet"], moisture:"postbake", weight:"light", presence:"accent",
    note:"Post-bake always — wilts and blackens in oven",
    qty:{ unit:"bunch", yield_g:30, per_pizza_g:5, per_pizza_oz:0.2, shared_yield:6, min_purchase:1 },
  },
  {
    id:"dried_oregano", name:"Dried oregano",
    layer:"finish", cuisine:["neapolitan","greek","american","levantine","turkish"],
    profile:"T", sauceFamilies:["tomato","dairy","herb","nosause"],
    stores:["sara","cm"], postbake:true,
    flavorNotes:["herb","bitter"], moisture:"postbake", weight:"light", presence:"accent",
    note:"Post-bake or last 30s — essential on marinara and Greek pies",
    qty:{ unit:"jar", yield_g:0, per_pizza_g:0, per_pizza_tsp:0.5, shared_yield:40, pantry:true, min_purchase:1 },
  },
  {
    id:"fresh_mint", name:"Fresh mint",
    layer:"finish", cuisine:["levantine","turkish","greek","northafrican"],
    profile:"E", sauceFamilies:["tomato","dairy","herb","nosause","spicepaste"],
    stores:["sara","cm"], postbake:true,
    flavorNotes:["herb","fresh","sweet"], moisture:"postbake", weight:"light", presence:"accent",
    note:"Post-bake — Turkish and Levantine classic finish",
    qty:{ unit:"bunch", yield_g:20, per_pizza_g:4, per_pizza_oz:0.1, shared_yield:5, min_purchase:1 },
  },
  {
    id:"dried_mint", name:"Dried mint",
    layer:"finish", cuisine:["levantine","turkish","greek","northafrican"],
    profile:"E", sauceFamilies:["tomato","dairy","herb","nosause"],
    stores:["sara"], postbake:true,
    flavorNotes:["herb","fresh"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Dried and crumbled mint — more concentrated than fresh, used differently in Levantine cooking.",
    note:"Rub between fingers before sprinkling — releases oils",
    qty:{ unit:"jar", yield_g:0, per_pizza_g:0, per_pizza_tsp:0.5, shared_yield:40, pantry:true, min_purchase:1 },
  },
  {
    id:"fresh_cilantro", name:"Fresh cilantro",
    layer:"finish", cuisine:["mexican","indian","northafrican","levantine"],
    profile:"T", sauceFamilies:["tomato","spicepaste","herb"],
    stores:["sara","cm"], postbake:true,
    flavorNotes:["herb","fresh","acid"], moisture:"postbake", weight:"light", presence:"accent",
    note:"Post-bake only",
    qty:{ unit:"bunch", yield_g:20, per_pizza_g:4, per_pizza_oz:0.1, shared_yield:5, min_purchase:1 },
  },
  {
    id:"flat_parsley", name:"Flat-leaf parsley",
    layer:"finish", cuisine:["levantine","turkish","northafrican","greek","neapolitan"],
    profile:"T", sauceFamilies:["tomato","dairy","herb","nosause","spicepaste"],
    stores:["sara","cm"], postbake:true,
    flavorNotes:["herb","fresh","bitter"], moisture:"postbake", weight:"light", presence:"accent",
    note:"Post-bake — universal finish herb",
    qty:{ unit:"bunch", yield_g:20, per_pizza_g:4, per_pizza_oz:0.1, shared_yield:5, min_purchase:1 },
  },
  {
    id:"sumac_finish", name:"Sumac (dusted)",
    layer:"finish", cuisine:["levantine","turkish","northafrican","greek"],
    profile:"E", sauceFamilies:["tomato","dairy","herb","nosause"],
    stores:["sara"], postbake:true,
    flavorNotes:["acid","fresh"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Ground dried sumac berry — intensely lemony and tart. Essential Levantine spice.",
    note:"Post-bake — lemony, essential on Levantine and Turkish pies",
    qty:{ unit:"jar", yield_g:0, per_pizza_g:0, per_pizza_tsp:1, shared_yield:30, pantry:true, min_purchase:1 },
  },
  {
    id:"zaatar_finish", name:"Za'atar (sprinkled)",
    layer:"finish", cuisine:["levantine","turkish","northafrican"],
    profile:"E", sauceFamilies:["tomato","dairy","herb","nosause"],
    stores:["sara"], postbake:true,
    flavorNotes:["herb","acid","crunch"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Blend of dried thyme, sumac, sesame and salt — earthy, herbaceous, nutty.",
    note:"Post-bake or last 30 seconds",
    qty:{ unit:"jar", yield_g:0, per_pizza_g:0, per_pizza_tbsp:1, shared_yield:20, pantry:true, min_purchase:1 },
  },
  {
    id:"chaat_masala", name:"Chaat masala (dusted)",
    layer:"finish", cuisine:["indian"],
    profile:"T", sauceFamilies:["spicepaste","dairy"],
    stores:["cm"], postbake:true,
    flavorNotes:["acid","spice","umami"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Indian spice blend — tangy, salty, cumin-forward with amchur (dried mango powder).",
    note:"Post-bake — tangy, umami, essential on Indian pies",
    qty:{ unit:"jar", yield_g:0, per_pizza_g:0, per_pizza_tsp:0.5, shared_yield:40, pantry:true, min_purchase:1 },
  },
  {
    id:"finish_evoo", name:"EVOO (finishing drizzle)",
    layer:"finish", cuisine:["neapolitan","greek","levantine","turkish","northafrican","american"],
    profile:"T", sauceFamilies:["tomato","dairy","herb","nosause","spicepaste"],
    stores:["sara","cm"], postbake:true,
    flavorNotes:["fat","fresh"], moisture:"postbake", weight:"light", presence:"accent",
    note:"Post-bake always — use your best bottle here",
    qty:{ unit:"bottle", yield_g:750, per_pizza_g:0, per_pizza_tbsp:1, shared_yield:50, pantry:true, min_purchase:1 },
  },
  {
    id:"lemon_zest", name:"Lemon zest",
    layer:"finish", cuisine:["greek","levantine","northafrican","neapolitan"],
    profile:"E", sauceFamilies:["tomato","dairy","herb","nosause"],
    stores:["sara","cm"], postbake:true,
    flavorNotes:["acid","fresh","herb"], moisture:"postbake", weight:"light", presence:"accent",
    note:"Post-bake — brightens everything, criminally underused",
    qty:{ unit:"lemon", yield_g:0, per_pizza_g:0, per_pizza_unit:0.3, min_purchase:1 },
  },
  {
    id:"hot_honey", name:"Hot honey drizzle",
    layer:"finish", cuisine:["american","neapolitan"],
    profile:"E", sauceFamilies:["tomato","dairy","spicepaste","nosause"],
    stores:["cm"], postbake:true,
    flavorNotes:["sweet","heat","fat"], moisture:"postbake", weight:"light", presence:"accent",
    note:"Calabrian style — post-bake drizzle. Essential with gorgonzola.",
    qty:{ unit:"bottle", yield_g:0, per_pizza_g:0, per_pizza_tbsp:0.5, shared_yield:30, pantry:true, min_purchase:1 },
  },
  {
    id:"balsamic_glaze", name:"Balsamic glaze (Modena)",
    layer:"finish", cuisine:["neapolitan","american","greek"],
    profile:"E", sauceFamilies:["tomato","dairy","nosause","herb"],
    stores:["cm"], postbake:true,
    flavorNotes:["sweet","acid","umami"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Reduced balsamic vinegar from Modena — thick, sweet-sour syrup. Not regular balsamic vinegar.",
    note:"Post-bake drizzle — classic with burrata, bresaola, arugula",
    qty:{ unit:"bottle", yield_g:0, per_pizza_g:0, per_pizza_tbsp:0.5, shared_yield:30, pantry:true, min_purchase:1 },
  },
  {
    id:"pomegranate_mol", name:"Pomegranate molasses",
    layer:"finish", cuisine:["levantine","northafrican","turkish"],
    profile:"C", sauceFamilies:["tomato","dairy","herb","spicepaste"],
    stores:["sara"], postbake:true,
    flavorNotes:["sweet","acid","umami"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Reduced pomegranate juice — thick, intensely sweet-sour. Used across Levantine and Turkish cooking.",
    note:"Post-bake — use sparingly, very concentrated",
    qty:{ unit:"bottle", yield_g:0, per_pizza_g:0, per_pizza_tsp:1, shared_yield:30, pantry:true, min_purchase:1 },
  },
  {
    id:"tahini_drizzle", name:"Tahini drizzle",
    layer:"finish", cuisine:["levantine","northafrican","turkish"],
    profile:"E", sauceFamilies:["tomato","dairy","herb","nosause"],
    stores:["sara"], postbake:true,
    flavorNotes:["fat","umami","acid"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Sesame paste thinned with lemon juice — nutty, rich, pairs with almost any Levantine pie.",
    note:"Thin with lemon juice before drizzling — post-bake",
    qty:{ unit:"jar", yield_g:0, per_pizza_g:0, per_pizza_tbsp:1, shared_yield:20, pantry:true, min_purchase:1 },
  },
  {
    id:"red_chili_flakes", name:"Dried red chili flakes",
    layer:"finish", cuisine:["neapolitan","american","indian","turkish","levantine"],
    profile:"T", sauceFamilies:["tomato","dairy","spicepaste","nosause"],
    stores:["sara","cm"], postbake:true,
    flavorNotes:["heat","spice"], moisture:"postbake", weight:"light", presence:"accent",
    note:"Calabrian preferred for Neapolitan, Aleppo for Levantine — post-bake",
    qty:{ unit:"jar", yield_g:0, per_pizza_g:0, per_pizza_tsp:0.25, shared_yield:60, pantry:true, min_purchase:1 },
  },
  {
    id:"calabrian_chili_oil", name:"Calabrian chili oil (finish)",
    layer:"finish", cuisine:["neapolitan","american"],
    profile:"E", sauceFamilies:["tomato","dairy","spicepaste","nosause"],
    stores:["cm"], postbake:true,
    flavorNotes:["heat","fat","smoke"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Oily, fruity Calabrian chili condiment — different from dried flakes.",
    note:"Post-bake drizzle — a little goes far",
    qty:{ unit:"jar", yield_g:0, per_pizza_g:0, per_pizza_tsp:1, shared_yield:20, pantry:true, min_purchase:1 },
  },
  {
    id:"aleppo_pepper", name:"Aleppo pepper flakes",
    layer:"finish", cuisine:["levantine","turkish","northafrican","american"],
    profile:"E", sauceFamilies:["tomato","dairy","herb","spicepaste","nosause"],
    stores:["sara"], postbake:true,
    flavorNotes:["heat","acid","fat"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Syrian dried chili — fruity, moderately hot, oily texture. Completely different from regular chili flakes.",
    note:"Post-bake — use instead of regular chili flakes on Levantine and Turkish pies",
    qty:{ unit:"jar", yield_g:0, per_pizza_g:0, per_pizza_tsp:0.5, shared_yield:40, pantry:true, min_purchase:1 },
  },
  {
    id:"kashmiri_chili", name:"Kashmiri chili (dusted)",
    layer:"finish", cuisine:["indian"],
    profile:"E", sauceFamilies:["spicepaste","dairy"],
    stores:["cm"], postbake:true,
    flavorNotes:["heat","sweet","spice"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Mild Indian chili with deep red color — more about color and gentle warmth than heat.",
    note:"Post-bake dust — vibrant red color, mild warmth",
    qty:{ unit:"jar", yield_g:0, per_pizza_g:0, per_pizza_tsp:0.5, shared_yield:40, pantry:true, min_purchase:1 },
  },
  {
    id:"dukkah", name:"Dukkah (sprinkled)",
    layer:"finish", cuisine:["northafrican","levantine","greek"],
    profile:"C", sauceFamilies:["dairy","herb","nosause","tomato"],
    stores:["sara"], postbake:true,
    flavorNotes:["crunch","herb","umami","fat"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Egyptian blend of roasted nuts, sesame, coriander and cumin — crunchy, aromatic, textural.",
    note:"Post-bake — pairs with labneh or goat cheese pies",
    qty:{ unit:"bag", yield_g:0, per_pizza_g:0, per_pizza_tbsp:1, shared_yield:15, pantry:true, min_purchase:1 },
  },
  {
    id:"urfa_biber", name:"Urfa biber / Isot pepper",
    layer:"finish", cuisine:["turkish","levantine"],
    profile:"C", sauceFamilies:["tomato","dairy","spicepaste","nosause"],
    stores:["sara"], postbake:true,
    flavorNotes:["smoke","sweet","heat","fat"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Turkish dried chili from Urfa — also sold as Isot biber or Isot pepper. Dark burgundy, smoky, raisin-like sweetness.",
    note:"Post-bake — dark, smoky, complex. Look for 'Isot biber' if you can't find Urfa",
    qty:{ unit:"jar", yield_g:0, per_pizza_g:0, per_pizza_tsp:0.5, shared_yield:40, pantry:true, min_purchase:1 },
  },
  {
    id:"pickled_red_onion", name:"Pickled red onion",
    layer:"finish", cuisine:["mexican","american","indian","levantine"],
    profile:"E", sauceFamilies:["tomato","spicepaste","dairy"],
    stores:["sara","cm"], postbake:true,
    flavorNotes:["acid","brine","fresh","crunch"], moisture:"postbake", weight:"light", presence:"accent",
    note:"Post-bake contrast — make or buy jarred",
    qty:{ unit:"jar", yield_g:0, per_pizza_g:0, per_pizza_tbsp:2, shared_yield:8, pantry:true, min_purchase:1 },
  },
  {
    id:"arugula", name:"Arugula (dressed)",
    layer:"finish", cuisine:["neapolitan","greek","american"],
    profile:"E", sauceFamilies:["tomato","dairy","nosause"],
    stores:["sara","cm"], postbake:true,
    flavorNotes:["bitter","fresh","acid","herb"], moisture:"postbake", weight:"light", presence:"supporting",
    note:"Toss in lemon + EVOO — drape over hot pizza post-bake. Classic with bresaola.",
    qty:{ unit:"bag (80g)", yield_g:80, per_pizza_g:20, per_pizza_oz:0.7, shared_yield:4, min_purchase:1 },
  },
  {
    id:"mango_chutney", name:"Mango chutney drizzle",
    layer:"finish", cuisine:["indian"],
    profile:"E", sauceFamilies:["spicepaste","dairy"],
    stores:["cm"], postbake:true,
    flavorNotes:["sweet","acid","spice"], moisture:"postbake", weight:"light", presence:"accent",
    note:"Thin with warm water — post-bake drizzle only",
    qty:{ unit:"jar", yield_g:0, per_pizza_g:0, per_pizza_tbsp:1, shared_yield:15, pantry:true, min_purchase:1 },
  },
  {
    id:"lime_crema", name:"Lime crema",
    layer:"finish", cuisine:["mexican"],
    profile:"T", sauceFamilies:["tomato","spicepaste"],
    stores:["cm"], postbake:true,
    flavorNotes:["acid","cream","fat"], moisture:"postbake", weight:"light", presence:"accent",
    note:"Sour cream + fresh lime juice — post-bake dollop",
    qty:{ unit:"sour cream (200g)", yield_g:200, per_pizza_g:30, per_pizza_oz:1.1, shared_yield:6, min_purchase:1 },
  },
  {
    id:"green_harissa", name:"Green harissa drizzle",
    layer:"finish", cuisine:["northafrican","levantine","turkish"],
    profile:"C", sauceFamilies:["herb","tomato","spicepaste"],
    stores:["sara"], postbake:true,
    flavorNotes:["herb","heat","acid"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Herb-based harissa — fresher, greener and less smoky than red harissa.",
    note:"Post-bake drizzle — herb-forward contrast",
    qty:{ unit:"jar", yield_g:0, per_pizza_g:0, per_pizza_tbsp:1, shared_yield:10, pantry:true, min_purchase:1 },
  },
  {
    id:"parmigiano", name:"Parmigiano-Reggiano (shaved)",
    layer:"finish", cuisine:["neapolitan","american","greek"],
    profile:"T", sauceFamilies:["tomato","dairy","nosause","herb"],
    stores:["cm"], postbake:true,
    flavorNotes:["umami","acid","fat","crunch"], moisture:"postbake", weight:"light", presence:"supporting",
    desc:"Aged Italian hard cheese — deep umami, nutty, complex. Always shaved post-bake, never melted.",
    note:"Post-bake always — shave with peeler over hot pizza",
    qty:{ unit:"wedge (100g)", yield_g:100, per_pizza_g:20, per_pizza_oz:0.7, shared_yield:5, min_purchase:1 },
  },
  {
    id:"pecorino", name:"Pecorino Romano (shaved)",
    layer:"finish", cuisine:["neapolitan","american"],
    profile:"T", sauceFamilies:["tomato","dairy","nosause"],
    stores:["cm"], postbake:true,
    flavorNotes:["brine","umami","acid"], moisture:"postbake", weight:"light", presence:"supporting",
    desc:"Aged Italian sheep's milk cheese — saltier and sharper than Parmigiano.",
    note:"Post-bake shave — saltier than Parmigiano, use less",
    qty:{ unit:"wedge (100g)", yield_g:100, per_pizza_g:15, per_pizza_oz:0.5, shared_yield:6, min_purchase:1 },
  },
  {
    id:"toasted_walnuts", name:"Toasted walnuts",
    layer:"finish", cuisine:["neapolitan","american","northafrican","greek"],
    profile:"E", sauceFamilies:["dairy","nosause","tomato"],
    stores:["sara","cm"], postbake:true,
    flavorNotes:["fat","crunch","bitter","umami"], moisture:"postbake", weight:"light", presence:"accent",
    note:"Toast in dry pan first — essential with gorgonzola and honey",
    qty:{ unit:"bag (100g)", yield_g:100, per_pizza_g:20, per_pizza_oz:0.7, shared_yield:5, min_purchase:1 },
  },
  {
    id:"toasted_pine_nuts", name:"Toasted pine nuts",
    layer:"finish", cuisine:["neapolitan","levantine","northafrican","greek"],
    profile:"E", sauceFamilies:["tomato","dairy","herb","nosause"],
    stores:["sara","cm"], postbake:true,
    flavorNotes:["fat","crunch","sweet","umami"], moisture:"postbake", weight:"light", presence:"accent",
    note:"Toast until golden — scatter post-bake",
    qty:{ unit:"bag (100g)", yield_g:100, per_pizza_g:15, per_pizza_oz:0.5, shared_yield:6, min_purchase:1 },
  },
  {
    id:"pistachios", name:"Pistachios (crushed)",
    layer:"finish", cuisine:["levantine","northafrican","neapolitan"],
    profile:"E", sauceFamilies:["dairy","nosause","herb"],
    stores:["sara","cm"], postbake:true,
    flavorNotes:["fat","crunch","sweet","herb"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Crushed pistachios as finish — Sicilian pistachio pizza is a real and wonderful thing.",
    note:"Crush roughly — post-bake scatter over ricotta or burrata pies",
    qty:{ unit:"bag (100g)", yield_g:100, per_pizza_g:15, per_pizza_oz:0.5, shared_yield:6, min_purchase:1 },
  },
  {
    id:"sesame_seeds", name:"Toasted sesame seeds",
    layer:"finish", cuisine:["turkish","levantine","northafrican","indian"],
    profile:"T", sauceFamilies:["tomato","dairy","herb","nosause","spicepaste"],
    stores:["sara"], postbake:true,
    flavorNotes:["crunch","fat","umami"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Toasted white or black sesame — nutty, subtle, essential in Turkish and Levantine baking.",
    note:"Post-bake scatter — toast first in dry pan",
    qty:{ unit:"bag", yield_g:0, per_pizza_g:0, per_pizza_tsp:1, shared_yield:30, pantry:true, min_purchase:1 },
  },
  {
    id:"nigella_seeds", name:"Nigella seeds (kalonji)",
    layer:"finish", cuisine:["turkish","indian","levantine"],
    profile:"C", sauceFamilies:["spicepaste","dairy","nosause"],
    stores:["sara"], postbake:true,
    flavorNotes:["bitter","spice","crunch"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"Black seeds with onion-like, slightly smoky flavor — also called black cumin or kalonji.",
    note:"Post-bake scatter — very small amount, distinctive flavor",
    qty:{ unit:"jar", yield_g:0, per_pizza_g:0, per_pizza_tsp:0.25, shared_yield:60, pantry:true, min_purchase:1 },
  },
  {
    id:"smoked_paprika", name:"Smoked paprika (dusted)",
    layer:"finish", cuisine:["northafrican","turkish","american","greek"],
    profile:"T", sauceFamilies:["tomato","dairy","spicepaste","nosause"],
    stores:["sara","cm"], postbake:true,
    flavorNotes:["smoke","sweet","spice"], moisture:"postbake", weight:"light", presence:"accent",
    note:"Post-bake dust — Spanish smoked, not sweet paprika",
    qty:{ unit:"jar", yield_g:0, per_pizza_g:0, per_pizza_tsp:0.5, shared_yield:40, pantry:true, min_purchase:1 },
  },
  {
    id:"truffle_oil", name:"Truffle oil (drizzle)",
    layer:"finish", cuisine:["neapolitan","american"],
    profile:"E", sauceFamilies:["nosause","dairy","tomato"],
    stores:["cm"], postbake:true,
    flavorNotes:["umami","fat","sweet"], moisture:"postbake", weight:"light", presence:"anchor",
    desc:"Truffle-infused olive oil — earthy, aromatic, luxurious. Classic on bianca with mushrooms or potato.",
    note:"Post-bake only — a few drops, heat kills the aroma",
    qty:{ unit:"bottle", yield_g:0, per_pizza_g:0, per_pizza_tsp:1, shared_yield:20, pantry:true, min_purchase:1 },
  },
  {
    id:"maldon_salt", name:"Maldon salt flakes",
    layer:"finish", cuisine:["neapolitan","american","greek","levantine"],
    profile:"T", sauceFamilies:["tomato","dairy","nosause","herb","spicepaste"],
    stores:["cm"], postbake:true,
    flavorNotes:["brine","crunch"], moisture:"postbake", weight:"light", presence:"accent",
    desc:"English sea salt with large, crunchy flakes — adds mineral pop and texture.",
    note:"Post-bake — crumble over burrata, bresaola or any bianca pie",
    qty:{ unit:"box", yield_g:0, per_pizza_g:0, per_pizza_tsp:0.25, shared_yield:60, pantry:true, min_purchase:1 },
  },
];
